version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://username:password@db/your_db
      - SECRET_KEY=your_secret_key
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: your_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    command: celery -A app.scheduler.celery worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://username:password@db/your_db
      - SECRET_KEY=your_secret_key

volumes:
  db_data: 